// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBackground: typeof import('./components/BaseBackground.vue')['default']
    BaseBlock: typeof import('./components/BaseBlock.vue')['default']
    BaseNavigation: typeof import('./components/BaseNavigation.vue')['default']
    BaseNavigationTenant: typeof import('./components/BaseNavigationTenant.vue')['default']
    BasePageHeading: typeof import('./components/BasePageHeading.vue')['default']
    EpBrandLogo: typeof import('./components/EpBrandLogo.vue')['default']
    EpSplashEmblem: typeof import('./components/EpSplashEmblem.vue')['default']
    ErrorsView: typeof import('./components/ErrorsView.vue')['default']
    Index3View: typeof import('./components/Index3View.vue')['default']
    IndexTenantView: typeof import('./components/IndexTenantView.vue')['default']
    IndexView: typeof import('./components/IndexView.vue')['default']
    LoaderView: typeof import('./components/LoaderView.vue')['default']
    MenuView: typeof import('./components/MenuView.vue')['default']
    ModalChangePassword: typeof import('./components/ModalChangePassword.vue')['default']
    PageRouteProgress: typeof import('./components/PageRouteProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubjectAssignmentGradeTable: typeof import('./components/SubjectAssignmentGradeTable.vue')['default']
    TeacherSelectWithTooltip: typeof import('./components/TeacherSelectWithTooltip.vue')['default']
    TeachingAssignmentForm: typeof import('./components/TeachingAssignmentForm.vue')['default']
    TeachingScheduleGridPreview: typeof import('./components/TeachingScheduleGridPreview.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}
