import { defineStore } from "pinia";

export const useStudentStore = defineStore("student", {
  state: () => ({
    studentId: null,
    isLoading: false,
    response: null,
    paymentTypeOptions: [
      "NUEVO INGRESO",
      "REINSCRIPCIÓN",
      "REPOSICIÓN DE CREDENCIAL",
    ],
    paymentType: "NUEVO INGRESO",
    paymentMethodOptions: ["PAGO EN LÍNEA", "DEPÓSITO BANCARIO"],
    paymentMethod: "PAGO EN LÍNEA",
    form: {
      name: null,
      last_name_father: null,
      last_name_mother: null,
      nationality: null,
      curp: null,
      date_birth: null,
      place_birth: null,
      sex: null,
      weight: null,
      height: null,
      is_migrant: false,
      indigenous_group: null,
      indigenous_language: null,
      academic_group_id: null,
      disability: null,
      health_insurance: null,
      scholarship: null,
      address: null,
      colony: null,
      postal_code: null,
      municipality: null,
      federal_entity: null,
      home_phone: null,
      email: null,
      photo: null,
      academic: {
        udeei: null,
        origin_school: null,
        federal_entity_school: null,
      },
      relatives: {
        student_live_with: "ambos",
        father_data: {
          name: null,
          email: null,
          occupation: null,
          work_phone: null,
          relationship: null,
          work_address: null,
          phone_whatsapp: null,
        },
        mother_data: {
          name: null,
          email: null,
          occupation: null,
          work_phone: null,
          relationship: null,
          work_address: null,
          phone_whatsapp: null,
        },
        authorized_persons: [
          {
            name: null,
            relationship: null,
          },
          {
            name: null,
            relationship: null,
          },
          {
            name: null,
            relationship: null,
          },
        ],
        roommates: [
          {
            age: null,
            sex: null,
            name: null,
            occupation: null,
            scholarship: null,
            relationship: null,
          },
          {
            age: null,
            sex: null,
            name: null,
            occupation: null,
            scholarship: null,
            relationship: null,
          },
        ],
      },
      socioeconomics: {
        general: {
          what_works: null,
          student_works: false,
          working_hours: null,
          family_economy: null,
        },
        ownerships: {
          agua_drenaje: false,
          automovil: false,
          baño_propio: false,
          computadora: false,
          estereo: false,
          estufa: false,
          internet: false,
          kind_house: "Casa Rentada",
          lavadora: false,
          microondas: false,
          recamara_propia: false,
          refrigerador: false,
          tv_paga: false,
        },
        nutrition: {
          breakfast: {
            egg: false,
            milk: false,
            bread: false,
            fruit: false,
            cereal: false,
            fast_food: false,
          },
          lunch: {
            fish: false,
            meat: false,
            flour: false,
            fruit: false,
            fast_food: false,
            vegetable: false,
          },
          dinner: {
            egg: false,
            meat: false,
            milk: false,
            flour: false,
            coffee: false,
            fast_food: false,
          },
        },
      },
      healths: {
        current_general_status: "Sano",
        blood_type: "A positivo (A+)",
        chronic_disease: "no",
        has_medical_service: false,
        medical_service_number: "123243",
        medical_service_name: "IMSS",
        familiar_affection: {
          dope: false,
          cigar: false,
          drugs: false,
          coffee: false,
          nerve_pills: false,
          sleeping_pills: false,
          alcoholic_drinks: false,
        },
        medical_care: {
          glasses: false,
          tonsils: false,
          flatfoot: false,
          seizures: false,
          accidents: false,
          medicines: false,
          operations: false,
          hearing_problems: false,
          orthopedic_device: false,
          complete_vaccinations: false,
        },
      },
    },
    data_report: [],
    form_print: {},
    groups: [],
    grades: [],
  }),
  actions: {
    async getGrades() {
      const { data } = await api.get(`/lists/grades`);
      this.grades = data;
    },
    async getGroups() {
      const { data } = await api.get(`/lists/academic-groups`);
      this.groups = data.data;
    },
  },
});
